;(function($){
	/**
	 * 菜单公共部分，共用在每一个页面中
	 */
	var menu = $("<div class='head' id='head'>"
					+"<div class='head-title'>"
						+"<img src='images/index_logo.png' alt='壹帮帮' />"
						+"<span class='head-content'>"
							+"<p class='head-ch'>壹帮帮</p>"
							+"<p class='head-en'>one bangbang</p>"
						+"</span>"
					+"</div>"
					+"<a href='javascript:;' class='head-links'>"
						+"<img src='images/menu_icon.png' alt='菜单' />"
					+"</a>"
				+"</div>"
				+"<nav class='menu' id='menu'>"
					+"<div class='menu-head'>"
						+"<img src='images/return_icon.png' alt='返回上一级' class='menu-head-return' />"
						+"<img src='images/close_icon.png' alt='关闭页面' class='menu-head-close' />"
					+"</div>"
					+"<div class='menu-main'>"
						+"<ul class='menu-primary'>"
							+"<li>"
								+"<a href='index.html' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_home.png' alt='首页' />"
									+"<span>首页</span>"
								+"</a>"
							+"</li>"
							+"<li>"
								+"<a href='introduce.html' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_introduce.png' alt='产品介绍' />"
									+"<span>产品介绍</span>"
								+"</a>"
							+"</li>"
							+"<li>"
								+"<a href='/service' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_service.png' alt='产品服务' />"
									+"<span>产品服务</span>"
									+"<i class='next'><img src='images/nav/next_icon.png' alt='下一级' /></i>"
								+"</a>"
							+"</li>"
							+"<li>"
								+"<a href='app.html' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_app.png' alt='APP' />"
									+"<span>APP</span>"
								+"</a>"
							+"</li>"
							+"<li>"
								+"<a href='/help' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_help.png' alt='帮助中心' />"
									+"<span>帮助中心</span>"
									+"<i class='next'><img src='images/nav/next_icon.png' alt='下一级' /></i>"
								+"</a>"
							+"</li>"
							+"<li>"
								+"<a href='http://www.1bpcafe.com/' class='menu-item'>"
									+"<img src='images/nav/nav_light_white_shop.png' alt='网上商城' />"
									+"<span>网上商城</span>"
								+"</a>"
							+"</li>"
						+"</ul>"
					+"</div>"
					+"<div class='sub-menu'>"
						+"<div class='product-service'>"
							+"<a href='service.html' class='links'>"
								+"<img src='images/nav/nav_light_white_service.png' alt='产品服务' />"
								+"<span>产品服务</span>"
							+"</a>"
							+"<ul>"
								+"<li class='menu-item'><a href='business.html'>商家开店</a></li>"
								+"<li class='menu-item'><a href='opration.html'>运营推广</a></li>"
							+"</ul>"
						+"</div>"
						+"<div class='help-center'>"
							+"<a href='help.html' class='links'>"
								+"<img src='images/nav/nav_light_white_help.png' alt='帮助中心' />"
								+"<span>帮助中心</span>"
							+"</a>"
							+"<ul>"
								+"<li class='menu-item'><a href='advisory.html'>客服咨询</a></li>"
								+"<li class='menu-item'><a href='helpCenter.html'>帮助中心</a></li>"
							+"</ul>"
						+"</div>"
					+"</div>"
				+"</nav>");
	$('body').prepend(menu);
})(jQuery);